name: Docker Publishing

on:
  push:
    branches:
      - '*'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:

jobs:
  publish:

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.pcicdevops_at_dockerhub_username }}
          password: ${{ secrets.pcicdevops_at_dockerhub_password }}
          repository: pcic/geospatial-python
          tag_with_ref: true
